package org.flickit.assessment.data.annotation;

import org.hibernate.tuple.*;

public class ReferenceNumberValueGeneration implements AnnotationValueGeneration<ReferenceNumberValue> {

    String query;

    @Override
    public void initialize(ReferenceNumberValue annotation, Class<?> propertyType) {
        this.query = annotation.query();
    }

    /**
     * Generate value on INSERT
     *
     * @return when to generate the value
     */
    public GenerationTiming getGenerationTiming() {
        return GenerationTiming.INSERT;
    }

    /**
     * Returns null because the value is generated by the database.
     *
     * @return null
     */
    public ValueGenerator<?> getValueGenerator() {
        return null;
    }

    /**
     * Returns true because the value is generated by the database.
     *
     * @return true
     */
    public boolean referenceColumnInSql() {
        return true;
    }

    /**
     * Returns the database-generated value
     *
     * @return database-generated value
     */
    public String getDatabaseGeneratedReferencedColumnValue() {
        return query;
//        return "(SELECT nextval('fak_maturity_level_reference_number_seq'))";
    }
}
