package org.flickit.assessment.common.application.domain.assessment;

public enum AssessmentPermission {

    ANSWER_QUESTION,
    VIEW_REPORT_ASSESSMENT,
    CALCULATE_ASSESSMENT,
    CALCULATE_CONFIDENCE,
    CREATE_ASSESSMENT,
    DELETE_ASSESSMENT,
    VIEW_ASSESSMENT_LIST,
    VIEW_ASSESSMENT_PROGRESS,
    VIEW_ASSESSMENT,
    UPDATE_ASSESSMENT,
    VIEW_ATTRIBUTE_SCORE_DETAIL,
    ADD_EVIDENCE,
    DELETE_EVIDENCE,
    VIEW_ATTRIBUTE_EVIDENCE_LIST,
    VIEW_EVIDENCE_LIST,
    UPDATE_EVIDENCE,
    VIEW_ASSESSMENT_QUESTIONNAIRE_LIST,
    VIEW_QUESTIONNAIRE_QUESTIONS,
    VIEW_SUBJECT_PROGRESS,
    VIEW_SUBJECT_REPORT,
    CREATE_ADVICE,
    GRANT_USER_ASSESSMENT_ROLE,
    UPDATE_USER_ASSESSMENT_ROLE,
    DELETE_USER_ASSESSMENT_ROLE,
    GET_ASSESSMENT_USERS,
    VIEW_ANSWER_HISTORY_LIST
}
